travis:
  secure:
    BINSTAR_TOKEN: eWQO2T3eCLZ49qOGj292RANbulXoU91zTN9mOV2x3qjmpwQDagVA0ZU4Tl1QRScieR8I8jsfF/paG5MZMJ12phjar55BjgLIJp3EV3yr7OZ3o4IZ0/gPgeAHYK9YNhBQw6D5QHSdD/6yrnrRMl5GOYX0iYS4/UMONZqWEANPbziojq5DrIO8smuk5kaVXWRyJ0SJcrfP/RRXm4hP1/UjBQ8w2XbzJcAkCvL6LBYCDU3T8HL4a88GN56KU7gKynyVmimFWhHlrK41ni83ybWXrxplUBnkjS1VZ5uZ8XpnoWCbFKzIoNe6YtafISmsooPwbT1+sSDfV0iNj/4vbDeZeZvWtvnKNz3WoM3pCwiuEPx6FP5Fdnrq5TNpLcKrTTeY/S1MIqK86Ws/1/MogkphbUo/GsbwCRNkZcIYq+0VWyyyN9kZO24uTalXx/ZsnWWzWzb3F7tI1kIxUubtZ6xGTeVLTfwmZGVsReILsa5HKifweTF4iCSOLAVTv5ObUR+Cag09y6I4uJhcFUT6+8g8dhqHB8850Du03F5X4NrQX4fRDgNl8XS6yqWUtuo/fXatjYkDtHSnOyyMHhh1z7Lk4s+C/T9VAjOhzd0yvQFAZS2tHcxMswIsUABhg7LoAUEQdZjs9avkm10G4wF/l11WFLDuLutnHfOuMXOq5FJK/rM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
